<?php

namespace Likemusic\AutomatedUpdatePlayersGames\Helper\CountryCodeConverter;

use InvalidArgumentException;

class DonorLatinToSiteLatin
{
    private $donorLatinToSiteLatin = [
        "AFG" => "AFG",
        "ALB" => "ALB",
        "AND" => "AND",
        "UAE" => "ARE",
        "ARG" => "ARG",
        "ARM" => "ARM",
        "AUS" => "AUS",
        "AUT" => "AUT",
        "AZE" => "AZE",
        "BDI" => "BDI",
        "BEL" => "BEL",
        "BEN" => "BEN",
        "BUR" => "BFA",
        "BAN" => "BGD",
        "BUL" => "BGR",
        "BRN" => "BHR",
        "BAH" => "BHS",
        "BIH" => "BIH",
        "BLR" => "BLR",
        "BOL" => "BOL",
        "BRA" => "BRA",
        "BAR" => "BRB",
        "BRU" => "BRN",
        "BHU" => "BTN",
        "BOT" => "BWA",
        "CAF" => "CAF",
        "CAN" => "CAN",
        "SUI" => "CHE",
        "CHI" => "CHL",
        "CHN" => "CHN",
        "CIV" => "CIV",
        "CMR" => "CMR",
        "COD" => "COD",
        "CGO" => "COG",
        "COK" => "COK",
        "COL" => "COL",
        "COM" => "COM",
        "CPV" => "CPV",
        "CRC" => "CRI",
        "CUB" => "CUB",
        "CAY" => "CYM",
        "CYP" => "CYP",
        "CZE" => "CZE",
        "GER" => "DEU",
        "DEN" => "DNK",
        "DOM" => "DOM",
        "ECU" => "ECU",
        "EGY" => "EGY",
        "ERI" => "ERI",
        "ESP" => "ESP",
        "EST" => "EST",
        "ETH" => "ETH",
        "FIN" => "FIN",
        "FIJ" => "FJI",
        "FRA" => "FRA",
        "FSM" => "FSM",
        "GAB" => "GAB",
        "GBR" => "GBR",
        "GEO" => "GEO",
        "GHA" => "GHA",
        "GUI" => "GIN",
        "GAM" => "GMB",
        "GBS" => "GNB",
        "GEQ" => "GNQ",
        "GRE" => "GRC",
        "GRN" => "GRD",
        "GUA" => "GTM",
        "GUM" => "GUM",
        "GUY" => "GUY",
        "HKG" => "HKG",
        "HON" => "HND",
        "CRO" => "HRV",
        "HAI" => "HTI",
        "HUN" => "HUN",
        "INA" => "IDN",
        "IND" => "IND",
        "IRL" => "IRL",
        "IRI" => "IRN",
        "IRQ" => "IRQ",
        "ISL" => "ISL",
        "ISR" => "ISR",
        "ITA" => "ITA",
        "JAM" => "JAM",
        "JOR" => "JOR",
        "JPN" => "JPN",
        "KAZ" => "KAZ",
        "KEN" => "KEN",
        "KGZ" => "KGZ",
        "KIR" => "KIR",
        "SKN" => "KNA",
        "KOR" => "KOR",
        "KUW" => "KWT",
        "LAO" => "LAO",
        "LBN" => "LBN",
        "LBR" => "LBR",
        "LBA" => "LBY",
        "LCA" => "LCA",
        "LIE" => "LIE",
        "SRI" => "LKA",
        "LES" => "LSO",
        "LTU" => "LTU",
        "LUX" => "LUX",
        "LAT" => "LVA",
        "MAR" => "MAR",
        "MON" => "MCO",
        "MDA" => "MDA",
        "MAD" => "MDG",
        "MDV" => "MDV",
        "MEX" => "MEX",
        "MHL" => "MHL",
        "MKD" => "MKD",
        "MLI" => "MLI",
        "MLT" => "MLT",
        "MYA" => "MMR",
        "MNE" => "MNE",
        "MGL" => "MNG",
        "MOZ" => "MOZ",
        "MTN" => "MRT",
        "MRI" => "MUS",
        "MAW" => "MWI",
        "MAS" => "MYS",
        "NAM" => "NAM",
        "NIG" => "NER",
        "NGR" => "NGA",
        "NCA" => "NIC",
        "NED" => "NLD",
        "NOR" => "NOR",
        "NEP" => "NPL",
        "NRU" => "NRU",
        "NZL" => "NZL",
        "OMA" => "OMN",
        "PAK" => "PAK",
        "PAN" => "PAN",
        "PER" => "PER",
        "PHI" => "PHL",
        "PLW" => "PLW",
        "PNG" => "PNG",
        "POL" => "POL",
        "PUR" => "PRI",
        "PRK" => "PRK",
        "POR" => "PRT",
        "PAR" => "PRY",
        "PLE" => "PSE",
        "QAT" => "QAT",
        "ROU" => "ROU",
        "RUS" => "RUS",
        "RWA" => "RWA",
        "KSA" => "SAU",
        "SUD" => "SDN",
        "SEN" => "SEN",
        "SIN" => "SGP",
        "SOL" => "SLB",
        "SLE" => "SLE",
        "ESA" => "SLV",
        "SMR" => "SMR",
        "SOM" => "SOM",
        "SRB" => "SRB",
        "SSD" => "SSD",
        "STP" => "STP",
        "SUR" => "SUR",
        "SVK" => "SVK",
        "SLO" => "SVN",
        "SWE" => "SWE",
        "SWZ" => "SWZ",
        "SEY" => "SYC",
        "SYR" => "SYR",
        "CHA" => "TCD",
        "TOG" => "TGO",
        "THA" => "THA",
        "TJK" => "TJK",
        "TKM" => "TKM",
        "TLS" => "TLS",
        "TGA" => "TON",
        "TTO" => "TTO",
        "TUN" => "TUN",
        "TUR" => "TUR",
        "TUV" => "TUV",
        "TPE" => "TWN",
        "TAN" => "TZA",
        "UGA" => "UGA",
        "UKR" => "UKR",
        "URU" => "URY",
        "USA" => "USA",
        "UZB" => "UZB",
        "VIN" => "VCT",
        "VEN" => "VEN",
        "IVB" => "VGB",
        "ISV" => "VIR",
        "VIE" => "VNM",
        "VAN" => "VUT",
        "SAM" => "WSM",
        "YEM" => "YEM",
        "RSA" => "ZAF",
        "ZAM" => "ZMB",
        "ZIM" => "ZWE",
    ];

    public function getSiteLatinByDonorLatin($donorLatinCountryCode)
    {
        //$query = 'SELECT `site_latin_code` FROM `country_codes` WHERE `donor_latin_code` = ?';

        if (!array_key_exists($donorLatinCountryCode, $this->donorLatinToSiteLatin)) {
            throw new InvalidArgumentException('Unknown country code: '. $donorLatinCountryCode);
        }

        return $this->donorLatinToSiteLatin[$donorLatinCountryCode];
    }

}
